#directives
version: '3'

networks:
  inception: 
    name: inception_network

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks: 
      - inception
    restart: always 

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress_volume:/var/www/html
    networks: 
      - inception
    restart: always 

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$WORDPRESS_DB_PASSWORD
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
    volumes:
      - database_volume:/var/lib/mysql
    networks: 
      - inception
    restart: always

volumes:

  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /Users/tmarts/data/wordpress_volume
      o: bind
      type: none

  database_volume:
    name: database_volume
    driver: local
    driver_opts:
      device: /Users/tmarts/data/database_volume
      o: bind
      type: none
