#directives

networks:
  inception: 
    name: inception_network

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    restart: always 
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    secrets:
      - wp_user_pass
      - wp_admin_pass
      - db_pass
    volumes:
      - wordpress_volume:/var/www/html
    networks: 
      - inception
    restart: always 
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
       - db_root_pass
       - db_pass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P 3306 -uroot -p$$(cat /run/secrets/db_root_pass)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - database_volume:/var/lib/mysql
    networks: 
      - inception
    restart: always 

volumes:
  wordpress_volume:
    driver_opts:
      o: bind
      type: none
      device: /home/tmarts/data/wordpress_volume
  database_volume:
    driver_opts:
      o: bind
      type: none
      device: /home/tmarts/data/database_volume

secrets:
  db_pass:
    file: ../secrets/db_password.txt
  db_root_pass:
    file: ../secrets/db_root_password.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_password.txt
  wp_user_pass:
    file: ../secrets/wp_user_password.txt