#directives
version: ' 1.29.2'

networks:
  inception: 
    name: inception_network

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx_tm
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    restart: always 

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      # MYSQL_PASSWORD: /run/secrets/db_password
    expose:
      - 9000
    secrets:
       - db_root_password
       - db_password
    volumes:
      - wordpress_volume:/var/www/html
    networks: 
      - inception
    restart: always 

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_root_password
       - db_password
    # expose:
    #   - 3306
    volumes:
      - database_volume:/var/lib/mysql
    networks: 
      - inception
    restart: always

volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /Users/tmarts/data/wordpress_volume
      o: bind
      type: none
  database_volume:
    name: database_volume
    driver: local
    driver_opts:
      device: /Users/tmarts/data/database_volume
      o: bind
      type: none

secrets:
   db_password:
     file: ../secrets/db_password.txt
   db_root_password:
     file: ../secrets/db_root_password.txt