#directives
#version: '3' << obsolete in newer versions

networks:
  inception: 
    name: inception_network

services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    restart: always 

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      WP_USER_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - wp_user_password
      - wp_admin_password
      - db_password
    volumes:
      - wordpress_volume:/var/www/html
    networks: 
      - inception
    restart: always 

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_root_password
       - db_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P 3306 -uroot -p$$(cat /run/secrets/db_root_password)"]
      interval: 30m
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - database_volume:/var/lib/mysql
    networks: 
      - inception
    restart: always

volumes:
  wordpress_volume:
    driver_opts:
      o: bind
      type: none
      device: /Users/tmarts/Documents/Projects/Inception/wordpress_volume
  database_volume:
    driver_opts:
      o: bind
      type: none
      device: /Users/tmarts/Documents/Projects/Inception/database_volume

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
