#directives
#version: '3' << obsolete in newer versions

networks:
  inception: 
    name: inception_network

services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    restart: always 

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      WP_USER_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - wp_user_password
      - wp_admin_password
      - db_password
    volumes:
      - wordpress_volume:/var/www/html
    networks: 
      - inception
    restart: always 

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_root_password
       - db_password
    volumes:
      - database_volume:/var/lib/mysql
    networks: 
      - inception
    restart: always

volumes:
  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      device: /Users/tmarts/data/wordpress_volume
      o: bind
      type: none
  database_volume:
    name: database_volume
    driver_opts:
      device: /Users/tmarts/data/database_volume
      o: bind
      type: none

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
