#directives
version: '3'

networks:
  inception: 
    name: inception

services:
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /Users/tmarts/data/wp_volume:/var/www/html
    networks: 
      - inception
    restart: always 

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - /Users/tmarts/data/wp_volume:/var/www/html
    networks: 
      - inception
    restart: always 

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=$WORDPRESS_DB_PASSWORD
      - MARIADB_DATABASE=wordpress
    volumes:
      - /Users/tmarts/data/db_volume:/var/lib/database
    networks: 
      - inception
    restart: always

    